name: Gitleaks Scan

on:
  push:
    branches:
      - main  # Trigger saat ada push ke branch 'main'
  pull_request:
    branches:
      - main  # Trigger saat ada pull request ke 'main'

jobs:
  gitleaks-scan:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Gitleaks Configuration
        run: wget -O .gitleaks.toml https://raw.githubusercontent.com/tanookiai/central-configuration/master/config/gitleaks.toml

      - name: Confirm Gitleaks Configuration
        run: cat .gitleaks.toml

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml

  trivy-scan:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.tar.gz
          tar -xzf trivy_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy Image Scan
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL satrio8/microservice-app:latest
